package net.darkhax.ccodex;

import java.util.Arrays;

import net.darkhax.ccodex.proxy.ServerProxy;
import net.darkhax.ccodex.util.Config;
import net.darkhax.ccodex.util.Reference;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = Reference.ID, name = Reference.NAME, version = Reference.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class CustomCodex {

	@SidedProxy(serverSide = Reference.SERVER, clientSide = Reference.CLIENT)
	public static ServerProxy proxy;

	@Mod.Instance(Reference.ID)
	public static CustomCodex instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {

		getModMeta(event.getModMetadata());
		Config.createConfig(event);
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {

	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {

	}

	private void getModMeta(ModMetadata meta) {

		meta.authorList = Arrays.asList(new String[] { "Darkhax" });
		meta.logoFile = "null";
		meta.autogenerated = false;
		meta.credits = "Provided by Darkhax";
		meta.description = "This mod adds a custom codex for your server!";
		meta.url = "www.darkhax.net";
	}
}